const config = {
    API_URL: process.env.NEXT_PUBLIC_BASE_URL,
    USERNAME: process.env.NEXT_PUBLIC_USERNAME,
    PASSWORD: process.env.NEXT_PUBLIC_LOGIN_PASSWORD,
    TOKEN_SESSION: process.env.NEXT_PUBLIC_TOKEN_SESSION,
    GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_CLIENT_ID,
    GOOGLE_ACCESS_TOKEN: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_ACCESS_TOKEN,
    GOOGLE_CLIENT_SECRET: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_CLIENT_SECRET,
    CALENDAR_ID: process.env.NEXT_PUBLIC_REACT_APP_CALENDAR_ID,
    GOOGLE_API_KEY: process.env.NEXT_PUBLIC_REACT_APP_GOOGLE_API_KEY
};

export default config;
